"""adicionar itens no pedido

Revision ID: a66bc70089bf
Revises: 0e8e98f3209d
Create Date: 2026-05-10 17:05:05.098872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66bc70089bf'
down_revision: Union[str, Sequence[str], None] = '0e8e98f3209d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'itens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('itens', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
